all : singlec netc singler netr netrnoise

singlec : p1.c
	gcc -o single_neuron_classifier p1.c -lm

netc : p2.c
	gcc -o neural_net_classifier p2.c -lm

singler : p3.c
	gcc -o single_neuron_regressor p3.c -lm

netr : p4.c
	gcc -o neural_net_regressor p4.c -lm

netrnoise : p5.c
	gcc -o neural_net_regressor_noise p5.c -lm